# Dataset configurations
active_datasets: [bamboogle] # [nq, popqa, musique, bamboogle]

datasets:
  nq:
    source: RUC-NLPIR/FlashRAG_datasets
    subset: nq
    test_size: -1  # -1 for full dataset
    metrics: [exact_match, f1]

  popqa:
    source: RUC-NLPIR/FlashRAG_datasets
    subset: popqa
    test_size: -1
    metrics: [exact_match, f1]

  musique:
    source: RUC-NLPIR/FlashRAG_datasets
    subset: 2wikimultihopqa
    test_size: -1
    metrics: [exact_match, f1]

  bamboogle:
    source: RUC-NLPIR/FlashRAG_datasets
    subset: bamboogle
    test_size: -1
    metrics: [exact_match, f1]

evaluation:
  batch_size: 1 # not implemented yet
  max_parallel_searches: 1 # not implement yet
  checkpoint_every: 1
  output_dir: ./results